### ISSUE TITLE
Failed to attempt installation through composer

### ISSUE THREAD

**Issue by lucassouzavieira** [1fabiosoares/sculptor#1]
Cause: The package has as dependency a nonexistent package (another-vendor/package).

The attachment below shows the error when trying to install the package by the composer.

![sculptor](https://cloud.githubusercontent.com/assets/13005840/21938183/025ae5f8-d999-11e6-87d2-4f5996699de3.png)

**Comment by fabioars** [comment]
Your issues was fixed. Thanks for reporting.

![Issue #1 fixed](https://cloud.githubusercontent.com/assets/5921856/21950090/5f4e3c6e-d9d6-11e6-809a-9b845fdd4cf3.png)
